export const catalogFlowers = [
  {
    id: 1,
    order: 1,
    key: '',
    title: 'Grand rose fantasy',
    price: '$150',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/grant-rose-fantasy2.jpg',
    secondaryImage: '/img/grant-rose-fantasy.jpg',
    size: [
      { id: 1, name: '1 dozen', value: 1, price: '$150' },
      { id: 2, name: '2 dozen', value: 2, price: '$250' },
      { id: 3, name: '3 dozen', value: 3, price: '$350' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 2,
    order: 2,
    key: '',
    title: 'Elegant silence',
    price: '$150',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/elegant-silence.jpg',
    secondaryImage: '/img/elegant-silence2.jpg',
    size: [
      { id: 1, name: '1 dozen', value: 1, price: '$150' },
      { id: 2, name: '2 dozen', value: 2, price: '$250' },
      { id: 3, name: '3 dozen', value: 3, price: '$350' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 3,
    order: 3,
    key: '',
    title: 'Soft elegance luxury pink rose',
    price: '$100',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/soft-elegance-luxury-pink-rose.jpg',
    secondaryImage: '/img/soft-elegance-luxury-pink-rose2.jpg',
    size: [
      { id: 1, name: '1 dozen', value: 1, price: '$100' },
      { id: 2, name: '2 dozen', value: 2, price: '$180' },
      { id: 3, name: '3 dozen', value: 3, price: '$240' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 4,
    order: 4,
    key: '',
    title: 'Lemon luxe roses',
    price: '$150',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/lemon-luxe-roses.jpg',
    secondaryImage: '/img/lemon-luxe-roses2.jpg',
    size: [
      { id: 1, name: '1 dozen', value: 1, price: '$150' },
      { id: 2, name: '2 dozen', value: 2, price: '$250' },
      { id: 3, name: '3 dozen', value: 3, price: '$350' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 5,
    order: 5,
    key: '',
    title: 'Color riot',
    price: '$195',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/color-riot.jpg',
    // secondaryImage: '/img/color-riot2.jpg',
    size: [
      { id: 1, name: 'S', value: 1, price: '$195' },
      { id: 2, name: 'M', value: 3, price: '$255' },
    ],
    quantity: 1,
    soldOut: true,
    sale: false,
  },
  {
    id: 6,
    order: 6,
    key: '',
    title: 'Basket of grace',
    price: '$185',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/basket-of-grace.jpg',
    secondaryImage: '/img/basket-of-grace2.jpg',
    size: [
      { id: 1, name: 'S', value: 1, price: '$185' },
      { id: 2, name: 'M', value: 2, price: '$245' },
      { id: 3, name: 'L', value: 3, price: '$295' },
    ],
    quantity: 1,
    soldOut: true,
    sale: false,
  },
  {
    id: 7,
    order: 7,
    key: '',
    title: 'Royal rose bouquet',
    price: '$300',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/royal-rose-bouquet.jpg',
    secondaryImage: '/img/royal-rose-bouquet2.jpg',
    size: [
      { id: 1, name: '50 roses', value: 1, price: '$300' },
      { id: 2, name: '100 roses', value: 2, price: '$500' },
    ],
    quantity: 1,
    soldOut: true,
    sale: true,
  },
  {
    id: 8,
    order: 8,
    key: '',
    title: 'Royal white treasure bouquet',
    price: '$300',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/royal-white-treasure-bouquet.jpg',
    secondaryImage: '/img/royal-white-treasure-bouquet2.jpg',
    size: [
      { id: 1, name: '50 roses', value: 1, price: '$300' },
      { id: 2, name: '100 roses', value: 2, price: '$500' },
    ],
    quantity: 1,
    soldOut: true,
    sale: true,
  },
  {
    id: 9,
    order: 9,
    key: '',
    title: 'Sunburst deluxe bouquet',
    price: '$300',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/sunburst-deluxe-bouquet.jpg',
    secondaryImage: '/img/sunburst-deluxe-bouquet2.jpg',
    size: [
      { id: 1, name: '50 roses', value: 1, price: '$300' },
      { id: 2, name: '100 roses', value: 2, price: '$500' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 10,
    order: 10,
    key: '',
    title: 'Classic Red ',
    price: '$150',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/classic-red.jpg',
    secondaryImage: '/img/classic-red2.jpg',
    size: [
      { id: 1, name: '1 dozen', value: 1, price: '$150' },
      { id: 2, name: '2 dozen', value: 2, price: '$250' },
      { id: 3, name: '3 dozen', value: 3, price: '$350' },
    ],
  },
  {
    id: 11,
    order: 11,
    key: '',
    title: 'Royal Classic',
    price: '$300',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/royal-classic.jpg',
    secondaryImage: '/img/royal-classic2.webp',
    sale: true,
    size: [
      { id: 1, name: '50 roses', value: 1, price: '$300' },
      { id: 2, name: '100 roses', value: 2, price: '$500' },
    ],
  },
  {
    id: 12,
    order: 12,
    key: '',
    title: 'The Signature Blush',
    price: '$220',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/signature-blush.jpg',
    secondaryImage: '/img/signature-blush2.jpg',
    size: [
      { id: 1, name: 'M', value: 1, price: '$220' },
      { id: 2, name: 'L', value: 3, price: '$315' },
    ],
    quantity: 1,
    soldOut: true,
    sale: false,
  },
  {
    id: 13,
    order: 13,
    key: '',
    title: 'Vintage Grace',
    price: '$170',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/vintage-grace.jpg',
    secondaryImage: '/img/vintage-grace2.jpg',
    size: [
      { id: 1, name: '1 dozen', value: 1, price: '$170' },
      { id: 2, name: '2 dozen', value: 2, price: '$225' },
      { id: 3, name: '3 dozen', value: 3, price: '$305' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 14,
    order: 14,
    key: '',
    title: 'Golden apricot',
    price: '$170',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/golden-apricot1.jpg',
    secondaryImage: '/img/golden-apricot2.jpg',
    size: [
      { id: 1, name: '1 dozen', value: 1, price: '$170' },
      { id: 2, name: '2 dozen', value: 2, price: '$270' },
      { id: 3, name: '3 dozen', value: 3, price: '$370' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 15,
    order: 15,
    key: '',
    title: 'Velvet Dream',
    price: '$185',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/velvet-dream1.jpg',
    secondaryImage: '/img/velvet-dream2.jpg',
    size: [
      { id: 1, name: '1 dozen', value: 1, price: '$185' },
      { id: 2, name: '2 dozen', value: 2, price: '$285' },
      { id: 3, name: '3 dozen', value: 3, price: '$375' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 16,
    order: 16,
    key: '',
    title: 'Luxe Cloud',
    price: '$359',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/luxe-cloud1.jpg',
    secondaryImage: '/img/luxe-cloud2.jpg',
    size: [
      { id: 1, name: 'L', value: 1, price: '$359' },
      { id: 2, name: 'XL ', value: 3, price: '$419' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 17,
    order: 17,
    key: '',
    title: 'Bloom Souffle',
    price: '$249',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/bloom-souffle1.jpg',
    secondaryImage: '/img/bloom-souffle2.jpg',
    size: [
      { id: 1, name: 'M', value: 1, price: '$249' },
      { id: 2, name: 'L ', value: 3, price: '$319' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 18,
    order: 18,
    key: '',
    title: 'Dream Red',
    price: '$170',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/dream-red.jpg',
    secondaryImage: '/img/dream-red2.jpg',
    size: [
      { id: 1, name: '1 dozen', value: 1, price: '$170' },
      { id: 2, name: '2 dozen', value: 2, price: '$270' },
      { id: 3, name: '3 dozen', value: 3, price: '$370' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
  {
    id: 19,
    order: 19,
    key: '',
    title: 'Edel Luxe',
    price: '$170',
    currency: 'USD',
    currencySymbol: '$',
    priceTotal: 0,
    primaryImage: '/img/edel-luxe2.jpg',
    secondaryImage: '/img/edel-luxe1.jpg',
    size: [
      { id: 1, name: '1 dozen', value: 1, price: '$170' },
      { id: 2, name: '2 dozen', value: 2, price: '$270' },
      { id: 3, name: '3 dozen', value: 3, price: '$370' },
    ],
    quantity: 1,
    soldOut: false,
    sale: false,
  },
].sort((a, b) => a.id - b.id);
