export const catalogFlowers = [
  {
    id: 1,
    title: 'Grand rose fantasy',
    price: '$170',
    primaryImage: '/img/grant-rose-fantasy2.jpg',
    secondaryImage: '/img/grant-rose-fantasy.jpg',
    size: [
      { name: '1 dozen', value: 1, price: '$150' },
      { name: '2 dozen', value: 2, price: '$250' },
      { name: '3 dozen', value: 3, price: '$350' },
    ],
  },
  {
    id: 3,
    title: 'Elegant silence',
    price: '$150',
    primaryImage: '/img/elegant-silence.jpg',
    secondaryImage: '/img/elegant-silence2.jpg',
    size: [
      { name: '1 dozen', value: 1, price: '$150' },
      { name: '2 dozen', value: 2, price: '$230' },
      { name: '3 dozen', value: 3, price: '$300' },
    ],
  },
  {
    id: 4,
    title: 'Soft elegance luxury pink rose',
    price: '$150',
    primaryImage: '/img/soft-elegance-luxury-pink-rose.jpg',
    secondaryImage: '/img/soft-elegance-luxury-pink-rose2.jpg',
    size: [
      { name: '1 dozen', value: 1, price: '$150' },
      { name: '2 dozen', value: 2, price: '$230' },
      { name: '3 dozen', value: 3, price: '$300' },
    ],
  },
  {
    id: 8,
    title: 'Lemon luxe roses',
    price: '$150',
    primaryImage: '/img/lemon-luxe-roses.jpg',
    secondaryImage: '/img/lemon-luxe-roses2.jpg',
    size: [
      { name: '1 dozen', value: 1, price: '$150' },
      { name: '2 dozen', value: 2, price: '$230' },
      { name: '3 dozen', value: 3, price: '$300' },
    ],
  },
  {
    id: 11,
    title: 'Color riot',
    price: '$195',
    primaryImage: '/img/color-riot.jpg',
    secondaryImage: '',

    size: [
      { name: 'S', value: 1, price: '$195' },
      { name: 'M', value: 3, price: '$255' },
    ],
  },
  {
    id: 19,
    title: 'Basket of grace',
    price: '$185',
    primaryImage: '/img/basket-of-grace.jpg',
    secondaryImage: '',
    soldOut: true,
    size: [
      { name: 'S', value: 1, price: '$185' },
      { name: 'M', value: 2, price: '$245' },
      { name: 'L', value: 3, price: '$295' },
    ],
  },
  {
    id: 12,
    title: 'Royal rose bouquet',
    price: '$350',
    primaryImage: '/img/royal-rose-bouquet.jpg',
    secondaryImage: '/img/royal-rose-bouquet2.jpg',
    size: [
      { name: '50 roses', value: 1, price: '$350' },
      { name: '100 roses', value: 2, price: '$550' },
    ],
  },
  {
    id: 9,
    title: 'Royal white treasure bouquet',
    price: '$350',
    primaryImage: '/img/royal-white-treasure-bouquet.jpg',
    secondaryImage: '/img/royal-white-treasure-bouquet2.jpg',
    size: [
      { name: '50 roses', value: 1, price: '$350' },
      { name: '100 roses', value: 2, price: '$550' },
    ],
  },
  {
    id: 5,
    title: 'Sunburst deluxe bouquet',
    price: '$350',
    primaryImage: '/img/sunburst-deluxe-bouquet.jpg',
    secondaryImage: '/img/sunburst-deluxe-bouquet2.jpg',
    size: [
      { name: '50 roses', value: 1, price: '$350' },
      { name: '100 roses', value: 2, price: '$550' },
    ],
  },
  {
    id: 10,
    title: 'Classic Red ',
    price: '$150',
    primaryImage: '/img/classic-red.jpg',
    secondaryImage: '/img/classic-red2.jpg',
    size: [
      { name: '1 dozen', value: 1, price: '$150' },
      { name: '2 dozen', value: 2, price: '$230' },
      { name: '3 dozen', value: 3, price: '$300' },
    ],
  },
  {
    id: 2,
    title: 'Royal Classic',
    price: '$350',
    primaryImage: '/img/royal-classic.jpg',
    secondaryImage: '/img/royal-classic2.webp',
    size: [
      { name: '50 roses', value: 1, price: '$350' },
      { name: '100 roses', value: 2, price: '$550' },
    ],
  },
  {
    id: 18,
    title: 'The Signature Blush',
    price: '$220',
    primaryImage: '/img/signature-blush.jpg',
    secondaryImage: '',
    sale: true,
    size: [
      { name: 'M', value: 1, price: '$220' },
      { name: 'L', value: 3, price: '$315' },
    ],
  },
  {
    id: 17,
    title: 'Vintage Grace',
    price: '$170',
    primaryImage: '/img/vintage-grace.jpg',
    secondaryImage: '',
    size: [
      { name: '1 dozen', value: 1, price: '$170' },
      { name: '2 dozen', value: 2, price: '$225' },
      { name: '3 dozen', value: 3, price: '$305' },
    ],
  },
  {
    id: 16,
    title: 'Golden apricot',
    price: '$170',
    primaryImage: '/img/golden-apricot1.jpg',
    secondaryImage: '/img/golden-apricot2.jpg',
    size: [
      { name: '1 dozen', value: 1, price: '$170' },
      { name: '2 dozen', value: 2, price: '$250' },
      { name: '3 dozen', value: 3, price: '$330' },
    ],
  },
  {
    id: 14,
    title: 'Velvet Dream',
    price: '$170',
    primaryImage: '/img/velvet-dream1.jpg',
    secondaryImage: '/img/velvet-dream2.jpg',
    size: [
      { name: '1 dozen', value: 1, price: '$170' },
      { name: '2 dozen', value: 2, price: '$250' },
      { name: '3 dozen', value: 3, price: '$330' },
    ],
  },
  {
    id: 7,
    title: 'Luxe Cloud',
    price: '$359',
    primaryImage: '/img/luxe-cloud1.jpg',
    secondaryImage: '/img/luxe-cloud2.jpg',
    size: [
      { name: 'L', value: 1, price: '$359' },
      { name: 'XL ', value: 3, price: '$419' },
    ],
  },
  {
    id: 13,
    title: 'Bloom Souffle',
    price: '$249',
    primaryImage: '/img/bloom-souffle1.jpg',
    secondaryImage: '/img/bloom-souffle2.jpg',
    size: [
      { name: 'S', value: 1, price: '$249' },
      { name: 'M', value: 3, price: '$319' },
    ],
  },
  {
    id: 15,
    title: 'Dream Red',
    price: '$170',
    primaryImage: '/img/dream-red.jpg',
    secondaryImage: '/img/dream-red2.jpg',
    size: [
      { name: '1 dozen', value: 1, price: '$170' },
      { name: '2 dozen', value: 2, price: '$250' },
      { name: '3 dozen', value: 3, price: '$330' },
    ],
  },
  {
    id: 6,
    title: 'Edel Luxe',
    price: '$170',
    primaryImage: '/img/edel-luxe2.jpg',
    secondaryImage: '/img/edel-luxe1.jpg',
    size: [
      { name: '1 dozen', value: 1, price: '$170' },
      { name: '2 dozen', value: 2, price: '$250' },
      { name: '3 dozen', value: 3, price: '$330' },
    ],
  },
].sort((a, b) => a.id - b.id);
